language: node_js
node_js:
  - "node"
before_script:
  - npm install -g gulp
script:
  - npm install
  - gulp installRED
  - npm test
cache:
  bundler: true
  directories:
  - node_modules # NPM packages
notifications:
  email: false
  slack: snappyrobotics:hnC94BBFxWP0egOTG39EX3Jc
